# Основы NymPy

### Создаём массив

In [1]:
import numpy as np # импортируем numpy

In [2]:
a = [i for i in range(10)] # создаем список из 9 цифр с помощью цикла for

In [8]:
a # вызываем созданный список

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b = np.array(a) # Создаём массив NumPy присваивая его переменной b. Помещаем весь список в функцию array

In [9]:
b # Массив NumPy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # Можно сразу создать список в функции array

In [11]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array([i for i in range(10)]) # Можно также запускать в этой функции генератор

In [15]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [21]:
d = np.array(c) # Можно добавлять кортежи в массивы

In [22]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(d) # Узнаем ее тип с помощью объекта type

numpy.ndarray

ndarray - n размерный массив

### Типы данных массивов

In [24]:
d = np.array(a, dtype = float) # Можно в процессе поменять тип нашего массива, допустим на float

In [27]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]
# В отличии от списка и кортежа, nparray предпочитает данные одного типа 
# запишем в список тип данных с плавающей точкой

In [30]:
b = np.array(a, dtype = int) # Поменяем наш тип на int

In [31]:
b # Мы видим, что дробная часть исяезла и осталась просто 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.array(a, dtype = float # Пропищем float и все числа стали с плавающей точкой
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [33]:
b = np.array(a, dtype = str) # Пропищем его как строка и все числа стали типом str
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

Достаточно одного типа данных в массивах, чтобы весь массив принял его тип данных

In [34]:
b[3] # Индексация как в обычном питоне

'3'

In [36]:
b.ndim # Посмотреть размерность массива

1

In [37]:
b.shape # Размерность массива

(10,)

### Создадим 2D (двумерный) массив 

In [12]:
b = np.array([[i for i in range(10)],
             [t for t in range(10, 20)],
             [y for y in range(20, 30)]]) # Создаем массив с помощью генераторов

In [13]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [9]:
b.shape # Так как тут два числа, это значит, что у нас двумерный массив 3 ряда, 10 колонок

(3, 10)

In [10]:
b.size # Можно увидеть общее колличество элементов в матрице

30

In [15]:
b[:2, :3] # Делаем срез

array([[ 0,  1,  2],
       [10, 11, 12]])

In [16]:
b[1:, 5:] # Получаем матрицу 2х5

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [17]:
c = b[1:, 5:] # Это представление массива b view, по сути это ссылка
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

Если мы хотим отдельный независимый массив то:

In [19]:
c = b[1:, 5:].copy() # Нужно применить метод copy()

In [20]:
 c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

### DATA TYPES
Самыми популярными типами данных являются float32 и float64,
а так же int32 и int64

In [3]:
b = np.array([1., 2., 3.], dtype = np.float32)

In [4]:
b

array([1., 2., 3.], dtype=float32)

In [6]:
b = np.array([1., 2., 3.], dtype = np.float64)

In [7]:
b

array([1., 2., 3.])

In [8]:
b.dtype

dtype('float64')

In [11]:
b = np.array([1,2,3], dtype = np.int32)

In [12]:
b

array([1, 2, 3], dtype=int32)

In [13]:
b.dtype

dtype('int32')

In [14]:
b = np.array([1,2,3], dtype = np.int64)

In [15]:
b

array([1, 2, 3])

In [16]:
b.dtype

dtype('int64')

# Операции с векторами

Загрузим библиотеку NumPy

In [17]:
import numpy as np

Создадим два массива одинакового размера

In [18]:
a = np.array([0,1,2,3,4])

In [20]:
b = np.array([5,6,7,8,9])

### Сложение векторов

При сложении используется обычное сложение и получается точно такой же вектор

In [23]:
c = a + b

In [24]:
c

array([ 5,  7,  9, 11, 13])

Еще один способ:

In [25]:
c = np.add(a, b) # Берем функцию из библиотеки numpy - add

In [27]:
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [28]:
a = np.array([5,4,8,4,3])

In [29]:
b = np.array([3,5,7,1,3])

In [33]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

Альтернативный способ: 

In [34]:
d = np.subtract(a,b)
d

array([ 2, -1,  1,  3,  0])

При вычитании векторов, их размерность должна совпадать

In [35]:
a.shape == d.shape

True

### Умножение векторов на скаляр

In [37]:
a = np.array([5,4,8,4,3]) # Возьмем вектор а

In [38]:
a

array([5, 4, 8, 4, 3])

In [39]:
c = a * 2 # умножим вектор а на 2
c # и получаем вектор с

array([10,  8, 16,  8,  6])

Альтернативный способ умножения массива на скаляр:

In [41]:
a = np.array([5,4,8,4,3]) # Возьмем вектор а
a

array([5, 4, 8, 4, 3])

In [42]:
a.dot(-10) # Используем в качестве метода

array([-50, -40, -80, -40, -30])

In [43]:
np.dot(-10,a) # Здесь мы используем его в качестве функции

array([-50, -40, -80, -40, -30])

In [44]:
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

Для этого вектора должны быть одинаковой размерности

In [45]:
a = np.array([1,2,3]) # Для того чтобы их перемножить, мы должны поэлементно их перемножить, 
# а потом получившиеся числа сложить
b = np.array([4,5,6])

In [46]:
a.shape

(3,)

In [47]:
b.shape

(3,)

In [49]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2] # Разложим как это выглядит поэлементно
sp

32

В библиотеке numPy есть способ поэлегантнее, а именно использовать элемент @

In [50]:
a @ b

32

In [51]:
sp = np.dot(a, b) # Способ с помощью функции dot

In [52]:
sp

32

### Операции над матрицами

In [57]:
A = np.array([[0, 1], # Создадим матрицу А
             [2, 3],
             [4, 5]]

In [58]:
B = np.array([[6, 7], # Создадим матрицу А
             [8, 9],
             [10, 11]])

In [59]:
A.shape # В матрицах 3 строки и 2 столбца

(3, 2)

In [60]:
B.shape

(3, 2)

### Сложение матриц

In [64]:
C =  A + B # Но для такого сложения матрицы должны совпадать
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Альтернативный способ

In [65]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Вычитание матриц

In [67]:
A = np.array([[11, 13], # Создадим матрицу А
              [16, 9],
              [8, 15]])

In [58]:
B = np.array([[6, 7], # Создадим матрицу А
             [8, 9],
             [10, 11]])

In [68]:
D = A - B
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

In [69]:
D = np.subtract(A, B)
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

### Умножение матрицы на скаляр

Самый простой спозоб, это использовать умножение

In [71]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [73]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

Альтернатива DOT

In [75]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])

### Умножение матриц

In [76]:
X1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [77]:
X2 = np.array([[7,8,9,10],
               [11, 12, 13, 14]])

Число столбцов первой матрицы, должно равнятся числу строк второй

In [79]:
X1.shape[1] == X2.shape[0]

True

Для умножения матриц, чаще всего используют функцию dot()

In [80]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

В результате мы получаем матрицу Z, колличество строк совпадает с колличеством строк в первой матрице, а число столбцов, такое же как число столбцов у второй. Это правило.

Рассмотри как получается умножение матриц
Как получен элемент матрицы Z нулевой строки и нулевого столбца:

In [81]:
Z[0, 0]

29

In [82]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

Как получен элемент матрицы Z нулевой строки и первого столбца:

In [83]:
Z[0, 1]

32

In [84]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

32

### Модуль numpy.linalg: возведение матрицы в квадрат

In [85]:
A = np.array([[0, 1 ,2],
             [3, 4 ,5],
             [6, 7, 8]])

Если мы возводим матрицу в квадрат, то это равносильно умножению матрицы саму на себя. При этом число строк и столбцов в матрице должно совпадать

In [87]:
A_square = np.dot(A, A) #Можно использовать функцию dot
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [88]:
A_square = np.linalg.matrix_power(A, 2) # А можно используюя библиотеку linalg, воспользоваться функцией matrix
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### Создание единичной матрицы

Единичная матрица - квадратная матрица с единицами по главной диагонали и нулями в остальных ячейках

In [89]:
I = np.eye(3) # Еденичная матрица создается с помощью функции eye
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

При умножении любой матрицы на единичную, мы получаем ичходную матрицу

In [2]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Поэтому если мы ставим единичную матрицу на второе место, то ее размер должен быть 2х2

In [3]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [4]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

А если мы ее ставим на первое место, то ее размер будет 3х3

In [7]:
I = np.eye(3)

In [8]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Иногда при умножении производят Транспонирование матрицы

### Транспонирование матрицы

При этом строки матрицы становятся ее столбцами, а столбцы строками

In [10]:
A = np.array([[11,13], [16,9], [8,15]])
A

array([[11, 13],
       [16,  9],
       [ 8, 15]])

In [11]:
At = np.transpose(A)
At

array([[11, 16,  8],
       [13,  9, 15]])

Альтернатива, использование Т

In [12]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

Рассмотрим матрицы X и Y

In [13]:
X = np.array([[1,2], [3,4], [5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
Y = np.array([[0,1], [3,4], [6,7], [2,5]])
Y

array([[0, 1],
       [3, 4],
       [6, 7],
       [2, 5]])

In [15]:
Yt = Y.T #Нужно транспонировать матрицу Y
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

Так как в матрице Х два столбца, а в матрице Yt две строки, мы их можем перемножить

In [16]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

### Вычисление опеределителя и ранга матрицы

 Ранг матрицы говорит какое колличество строк или столбцов, является в данной матрице линейно независимыми

In [18]:
A = np.array([[0,1,2], [3,4,5], [6,7,8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
 np.linalg.det(A) # В этой матрице, определитель равен нулю

0.0

In [20]:
np.linalg.matrix_rank(A) # А ранг равен 2 это меньше чем число строк или столбцов в данной матрице

2

Пример 2 

In [21]:
B = np.array([[7,4,5], [8,3,2], [6,10,12]])
B

array([[ 7,  4,  5],
       [ 8,  3,  2],
       [ 6, 10, 12]])

In [22]:
np.linalg.det(B)

85.99999999999989

In [23]:
np.linalg.matrix_rank(B)

3

пример 3 Можно узнать только ранг, но не определитель, так как она не квадратная

In [24]:
C = np.array([[1,2], [3,4], [5,6]])
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.linalg.matrix_rank(C)

2

Мы не можем вычислить определитель, зато мы можем вычислить ранг

### Вычисление обратной матрицы

 Обратная матрица, это такая матрица, которая при умножении на исходную матрицу, дает единичную матрицу

In [21]:
B = np.array([[7,4,5], [8,3,2], [6,10,12]])
B

array([[ 7,  4,  5],
       [ 8,  3,  2],
       [ 6, 10, 12]])

Воспользуемся функцией инф из linalg

In [26]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

Мы получили обратную функцию В

 Если мы еще раз посчитаем обратную матрицу, то получим исходную

In [27]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

## Автоматическое создание массивов

С помощь функции zerro() можно создавать массивы, наполненые нулями

In [33]:
a = np.zeros((3,4)) # Массив из трех строк и 4 столбцов
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

С помощью функции ones() можно создавать массивы из единиц

In [34]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Последовательности чисел можно создавать с помощью функции arange()

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

по умолчанию ряд чисел начинается с нуля, но можно явно задать начало последовательности

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Последовательность с шагом 2

In [37]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

В обратном порядке с отрицательным числом

In [39]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

дробный шаг:

In [40]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

numpy.linspace- тоже самое, но нужно учитывать что правая граница(9,9) будет включена. 
Вместо шага указываем нужное число элементов

In [41]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Мы получаем 100 элементов

numpy.logspace() - тоже самое. Обе границы также включены, но это не сами числа, а степени числа 10 

In [42]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

**numpy.random.sample** - случайные числа с равномерным распределением [0.0, 1.0]

Случайное число:

In [44]:
np.random.sample()

0.7926484620367372

Одномерный массив из трех чисел:

In [45]:
np.random.sample(3)

array([0.9020597 , 0.60863143, 0.19765304])

Двумерный массив:

In [47]:
np.random.sample((2,3))

array([[0.16432927, 0.97759775, 0.84794765],
       [0.64728639, 0.1547308 , 0.85521276]])

Массив 48 х 64 х 3
Может использоваться для случайных изображений размером с высотой 48, шириной 64 и плотностью трех цветов на каждый пиксель


In [50]:
np.random.sample((48,64,3))

array([[[0.3294636 , 0.18059731, 0.65500714],
        [0.18442434, 0.44726414, 0.43289204],
        [0.89843569, 0.45533931, 0.47535029],
        ...,
        [0.70220309, 0.83217478, 0.6925364 ],
        [0.14054951, 0.20978237, 0.68627304],
        [0.42960076, 0.88026488, 0.95709945]],

       [[0.5802953 , 0.24162651, 0.58731539],
        [0.67869902, 0.14420663, 0.94540906],
        [0.59129993, 0.64958914, 0.16062806],
        ...,
        [0.89933435, 0.3608828 , 0.73137079],
        [0.5061529 , 0.23172005, 0.4268986 ],
        [0.89608344, 0.77746056, 0.19295753]],

       [[0.8023616 , 0.1589207 , 0.82004672],
        [0.037853  , 0.95220469, 0.93389339],
        [0.10893132, 0.0615372 , 0.6331734 ],
        ...,
        [0.98304245, 0.73173811, 0.52981496],
        [0.25526242, 0.05081905, 0.92620518],
        [0.95119777, 0.64142964, 0.9319433 ]],

       ...,

       [[0.04510363, 0.3051459 , 0.02673561],
        [0.89889185, 0.27976051, 0.08004378],
        [0.09232157, 0

**numpy.random.randn()** - нормальные числа с нормальным распределением
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [51]:
np.random.randn(10)

array([-0.7356377 ,  0.54187678,  0.20224982,  1.11319532,  1.50661578,
        0.92442841, -0.79240259, -0.63554291, -0.54048455, -0.03089959])

In [52]:
np.random.randn(3, 4)

array([[-1.96018442,  0.61800092, -0.22664581,  1.57060714],
       [-1.46676385, -0.10792063,  2.47999786,  3.33145039],
       [-0.59776667,  1.62381343, -0.98883095, -2.34757744]])

 **numpy.random.randint** - массив из целых чисел
 Например одномерный массив из 10 случайных чисел в промежутке [0, 100]

In [53]:
np.random.randint(0,100,10)# 0,100 - интервалб 10 - сколько чисел нужно

array([ 1, 12, 54, 12, 81, 56, 57, 31,  5, 40])

 Двумерный массив 3х4 из случайных чисел в промежутке 0, 10

In [55]:
np.random.randint(0, 10, (3,4)) 

array([[9, 7, 5, 0],
       [7, 6, 7, 0],
       [4, 3, 9, 9]])

**numpy.random.choice** - получаем случайные элементы из массива

In [56]:
b = np.array([1,5,2,7,3,8,6,4])

In [57]:
np.random.choice(b)

5

In [59]:
 np.random.choice(b, 4) # Получаем определенное колличество этих псевдослучайных чисел

array([1, 4, 5, 4])

**numpy.random.seed** - инициализация генератора случаных чисел
Могут использоваться для последующей воспроизводимости(будут генерироваться те же числа, если устоновить одинаковый seed)

In [60]:
np.random.seed(42)

In [63]:
np.random.randint(0,10,3)

array([2, 6, 7])

### Изменение формы массива

In [64]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Если нам нужен из этого **двумерный массив**, то мы используем функцию reshape

In [66]:
a.reshape(3,4) # Получаем двумерный массив из 3 строк и 4 столбцов

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Если мы знаем какое число строк нам нужно получить, но не знаем какое колличество столбцов получится, то:

In [67]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
# Можно указать требуемое число строк, а вместо столбцов поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
# Или наоборот -1 поставить в количество строк, а колличество столбцов указать нам необходимое
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Так же есть функция которая меняем массив на месте **inplase**

In [74]:
a.resize(3,4) # Если мы ее применим, то массив поменяет форму

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Получить из многомерного, одномерный массив можно с помощью функции **flatten**

In [76]:
a = a.flatten()

In [77]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

Для наглядности возьмем два массива с нулями и единицами

In [80]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

Соединение строк **вертикально**

In [83]:
v = np.vstack((a,b))

In [84]:
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

Так же можно это получить с помощью функции **concatenate**
При этом мы должны указать ось по которой мы хотим соединить 

In [86]:
np.concatenate((a,b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

Соединение столбцов **горизонтально**

In [87]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [89]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [90]:
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину (в третьем измерение)

In [91]:
d = np.dstack([a,b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

 ## Выбор данных из массива

In [95]:
a = np.random.randint(0,20,10)

In [96]:
a

array([16,  9, 15, 14, 14, 18, 11, 19,  2,  4])

Для того чтобы выбрать из массива числа больше 10:

In [97]:
a[a>10]

array([16, 15, 14, 14, 18, 11, 19])

In [98]:
a[(a > 10) & (a % 2 == 0)] #Если нужно выбрать два условия используем $

array([16, 14, 14, 18])

In [99]:
# Если нужно чтобы выборка отвечала одному из условий используем |
a[(a > 10) | (a % 3 == 0)]

array([16,  9, 15, 14, 14, 18, 11, 19])

**numpy.where** - первый вариант

In [100]:
a

array([16,  9, 15, 14, 14, 18, 11, 19,  2,  4])

Получаем не сами числа, а их индексы
Тут мы получаем индексы чисел, которые блольше 10

In [101]:
# Возвращает индексы чисел, удовлетворяющие условию
np.where(a > 10)

(array([0, 2, 3, 4, 5, 6, 7]),)

In [102]:
a[np.where(a>10)] 

array([16, 15, 14, 14, 18, 11, 19])

**np.where** - второй вариант

In [103]:
a = [1, 4, 7]
b = [9, 2, 5]

Мы указываем три аргумента, причем первый является маской

In [104]:
# Если в условии TRUE, то берем элемент из массива а
# если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сортировка

In [105]:
a = np.array([[1, 3, 9, 9],
             [5, 0, 1, 5],
             [2, 7, 3, 5]])

Сделаем сортировку по нулевому столбцу

In [106]:
a[[0,2,1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

Чтобы сделать автоматическую сортировку по определенной оси, используем функцию **argsort()**

In [107]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [108]:
a[:, 0].argsort()

array([0, 2, 1])

In [109]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

In [110]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
# inplace на месте
np.random.shuffle(a)

In [112]:
a

array([7, 9, 5, 8, 3, 1, 0, 4, 6, 2])

In [129]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [130]:
# inplace/
np.random.shuffle(a) # Смешивает только строки
a

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

### Математические действия с массивами

Применение математических действий ко всему массиву

In [132]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
# Логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [118]:
# Экспонента 
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [119]:
# Просумирует все элементы этого массива
a.sum()

21

In [121]:
# Суммирование значений по каждому столбцу

a.sum(axis = 0)

array([5, 7, 9])

In [122]:
# По каждой строке
a.sum(axis = 1)

array([ 6, 15])

Если мы прибавим число к этому массиву, то оно прибавится к каждому элементу этого массива

In [124]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
a + 10

array([[19, 20, 21],
       [16, 17, 18],
       [13, 14, 15],
       [10, 11, 12]])

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Поэлементное (не матричное) умножение

In [138]:
a = np.arange(12).reshape(3, -1)

In [139]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
b = np.arange(12,24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [141]:
a * b # Здесь поэлементно перемножаются все члены массива

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### BROADCASTING (на примере сложения)

In [142]:
 a = np.array([[2, 5],
               [3, 4],
               [6, 1]])

1 случай - совпадает только **число столбцов**

In [143]:
b = np.array([1, 2])

В данно случае у нас совпадает число столбцов

In [144]:
a + b # К каждой строке а прибавляется стока b

array([[3, 7],
       [4, 6],
       [7, 3]])

 2 случай - совпадает только число строк

In [146]:
c = np.array([[1],
             [2],
             [3]])

In [147]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

Складываются только столбцы, при чем два раза

### Статистические функции

In [149]:
a = np.random.randint(0, 12, (3, 4))
a

array([[11, 11,  6, 11],
       [ 7,  2,  0,  3],
       [ 1,  7,  3,  1]])

In [152]:
a.min() #Минимальное значение в массиве

0

In [154]:
a.min(axis = 0) #Минимум для каждого столбца

array([1, 2, 0, 1])

In [155]:
a.max(axis = 1) #Максимум для каждой строки

array([11,  7,  7])

In [156]:
a.max() # Максимум в массиве

11

In [157]:
a.mean(axis = 0) # Среднее значение для каждого столбца

array([6.33333333, 6.66666667, 3.        , 5.        ])

In [158]:
a.std(axis = 0) # Вычислить среднее квадратичное отклонение

array([4.10960934, 3.68178701, 2.44948974, 4.3204938 ])

### Запись или чтение массива из файла

In [159]:
np.save('a.npy', a)

In [160]:
b = np.load('a.npy')

In [161]:
b

array([[11, 11,  6, 11],
       [ 7,  2,  0,  3],
       [ 1,  7,  3,  1]])